/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SPI_EVE.h"
#include "SPI_EVE_PVT.h"
#include "MISO_EVE_aliases.h"
#include "MISO_EVE.h"
#include "MOSI_EVE_aliases.h"
#include "MOSI_EVE.h"
#include "SCLK_EVE_aliases.h"
#include "SCLK_EVE.h"
#include "nPD_EVE_aliases.h"
#include "nPD_EVE.h"
#include "SS_EVE_aliases.h"
#include "SS_EVE.h"
#include "Clock_1.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

