/***********************************************************************/
/*                                                                     */
/*  FILE        :SPI.c                                                 */
/*  DATE        :Tue, Aug. 23, 2013                                    */
/*  DESCRIPTION :SPI Functions                                         */
/*  CPU TYPE    :RX63N                                                 */
/*                                                                     */
/*  This file is generated by M. Reinschmidt - GLYN                    */
/*  NOTE:                                                              */
/*                                                                     */
/***********************************************************************/
#include "iodefine.h"                  
#include "spi.h"


void S_UART_SPI(void)
{
	SYSTEM.PRCR.WORD=0xA503u;
	MSTP(SCI3)=0;
	MPC.PWPR.BYTE=0x00;
	MPC.PWPR.BYTE=0x40;
	
  	MPC.P25PFS.BIT.PSEL = 0xA;  /* configrure for SRSPI */
  	MPC.P23PFS.BIT.PSEL = 0xA;  /* configrure for SRSPI */
 	MPC.P24PFS.BIT.PSEL = 0xA;  /* configrure for SRSPI */

  	PORT2.PMR.BYTE = 0x38 ;      /* Enable peripheral */


  	SCI3.SMR.BYTE=0x80;
  	SCI3.SSR.BYTE=0x84;
  	SCI3.SCMR.BYTE=0x7A; //MSB first //0x72 LSB First
  	SCI3.BRR=0x00;
  // 	SCI3.BRR=0x05;
 	SCI3.SCR.BYTE=0x00;

  	SCI3.SPMR.BYTE=0x00; // SSE Pin disabled in single-master system
 // 	SCI3.SPMR.BYTE=0x40; // SSE Pin disabled in single-master system // CLOCKPOL invert
  	SCI3.SPMR.BYTE=0x80; // SSE Pin disabled in single-master system // CLOCKPHASE

//	SCI3.SCR.BYTE=0x20;		// enable transmit
//	SCI3.SCR.BYTE=0x10;		// enable receive
	SCI3.SCR.BYTE=0x30;		// enable receive und transmit
}

void send_SPI(unsigned char data)
{
//M	SCI3.SCR.BYTE=0x20;		// enable transmit
	SCI3.TDR=data;
	while(SCI3.SSR.BIT.TEND==0);	
//M	SCI3.SCR.BYTE=0x00;		// disable transmit
//	SCI3.SCR.BYTE=0x10;		// enable receive
}

unsigned char read_SPI(void)
{
	unsigned char receive;
	
//M	SCI3.SCR.BYTE=0x30;		// enable receive
	receive=SCI3.RDR;
//M	SCI3.SCR.BYTE=0x00;		// disable transmit

return receive;
}

unsigned char USART_StatusGet(void)
{
	return SCI3.SSR.BIT.TEND;
}